#include "main.h"
#include "pwm.h"

/* TIM1 handle generated by CubeMX */
extern TIM_HandleTypeDef htim1;

static uint16_t pwm_arr = 0;

void PWM_Init(void)
{
    pwm_arr = __HAL_TIM_GET_AUTORELOAD(&htim1);
    PWM_SetDuty(0, 0, 0);
}

void PWM_Start(void)
{
    /* Main outputs */
    HAL_TIM_PWM_Start(&htim1, TIM_CHANNEL_1);
    HAL_TIM_PWM_Start(&htim1, TIM_CHANNEL_2);
    HAL_TIM_PWM_Start(&htim1, TIM_CHANNEL_3);

    /* Complementary outputs */
    HAL_TIMEx_PWMN_Start(&htim1, TIM_CHANNEL_1);
    HAL_TIMEx_PWMN_Start(&htim1, TIM_CHANNEL_2);
    HAL_TIMEx_PWMN_Start(&htim1, TIM_CHANNEL_3);
}

void PWM_Stop(void)
{
    /* Force safe duty first */
    PWM_SetDuty(0, 0, 0);

    HAL_TIM_PWM_Stop(&htim1, TIM_CHANNEL_1);
    HAL_TIM_PWM_Stop(&htim1, TIM_CHANNEL_2);
    HAL_TIM_PWM_Stop(&htim1, TIM_CHANNEL_3);

    HAL_TIMEx_PWMN_Stop(&htim1, TIM_CHANNEL_1);
    HAL_TIMEx_PWMN_Stop(&htim1, TIM_CHANNEL_2);
    HAL_TIMEx_PWMN_Stop(&htim1, TIM_CHANNEL_3);
}

void PWM_SetDuty(uint16_t du, uint16_t dv, uint16_t dw)
{
    if (du > pwm_arr) du = pwm_arr;
    if (dv > pwm_arr) dv = pwm_arr;
    if (dw > pwm_arr) dw = pwm_arr;

    __HAL_TIM_SET_COMPARE(&htim1, TIM_CHANNEL_1, du);
    __HAL_TIM_SET_COMPARE(&htim1, TIM_CHANNEL_2, dv);
    __HAL_TIM_SET_COMPARE(&htim1, TIM_CHANNEL_3, dw);
}

void PWM_SetDutyPercent(float du, float dv, float dw)
{
    if (du < 0) du = 0; if (du > 1) du = 1;
    if (dv < 0) dv = 0; if (dv > 1) dv = 1;
    if (dw < 0) dw = 0; if (dw > 1) dw = 1;

    PWM_SetDuty((uint16_t)(du * pwm_arr),
                (uint16_t)(dv * pwm_arr),
                (uint16_t)(dw * pwm_arr));
}
